### ISSUE TITLE
Force safer guzzle dependency of at least 6.2.1

### ISSUE THREAD

**Issue by bizmate** [iodatacenters/oktasdk-php#25]
As per change log in Guzzle https://github.com/guzzle/guzzle/blob/6.2.1/CHANGELOG.md

6.2.1 addresses HTTP_PROXY security vulnerability.

To make sure this the okta sdk is safer i would force that dependency. I will do a pr if i have time tonight.

**Comment by PHLAK** [comment]
OktaSDK-PHP already satisfies this constraint with the following requirement in composer.json file:

    "require": {
        ...
        "guzzlehttp/guzzle": "^6.1",
        ...
    }

The [caret operator](https://getcomposer.org/doc/articles/versions.md#caret) (`^`) instructs Composer to install the latest version available that is greater than or equal to 6.1.0 (>= 6.1.0) and less than 7.0.0 (< 7.0.0).  Since Guzzle 6.2.1 has been published and falls within these constraints it should be installed when running `composer require iodatacenters/oktasdk-php` or on a subsequent run of `composer update` if you installed OktaSDK-PHP prior to the release of Guzzle 6.2.1.  If it is not then another package you are using is constraining your Guzzle version and you should bring this to the attention of that package's maintainer.

**Comment by bizmate** [comment]
The problem with this is that it still allows the installation of versions 6.2.0. You should not just think about a greenfield project where you start by adding the sdk project. Instead, if a project has already installed an old version of guzzle for some reason, the sdk should force `^6.2.1` instead of accepting any older version.
